apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis.controlPlane.fullname" . }}
  labels:
    {{- include "aegis.controlPlane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  selector:
    {{- include "aegis.controlPlane.selectorLabels" . | nindent 4 }}
  ports:
    - name: admin
      port: {{ .Values.controlPlane.service.adminPort }}
      targetPort: admin
      protocol: TCP
    - name: metrics
      port: {{ .Values.controlPlane.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
