{{- if and .Values.controlPlane.apiToken (not .Values.controlPlane.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.controlPlane.fullname" . }}
  labels:
    {{- include "aegis.controlPlane.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.controlPlane.apiToken | b64enc }}
{{- end }}
