apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis.dataPlane.grpc.fullname" . }}
  labels:
    {{- include "aegis.dataPlane.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "aegis.dataPlane.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.dataPlane.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.dataPlane.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
