{{- if and .Values.dataPlane.tls.enabled (not .Values.dataPlane.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.dataPlane.fullname" . }}-tls
  labels:
    {{- include "aegis.dataPlane.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.dataPlane.tls.cert | b64enc }}
  tls.key: {{ .Values.dataPlane.tls.key | b64enc }}
{{- end }}
